### ISSUE TITLE
Objects are incorrectly fun

### ISSUE THREAD

**Issue by derekerdmann** [wadeanthony0100/noFun#2]
Calling `hasFun()` on objects that are named such that they should not be fun actually return true. Example:
```
require("nofun")
var Kayla = { }
Kayla.hasFun()
```

**Comment by derekerdmann** [comment]
Priority 0, severity 1. Pls fix. Blocking critical production deployment.

**Comment by derekerdmann** [comment]
Maintainer is completely unresponsive. I filed this bug and am getting zero support, how am I supposed to meet my deadlines with projects like this. Open source is overrated. Pls fix asap.

**Comment by wademauger** [comment]
I think this is intentional. Because Kayla is not inherently part of the object at hand, but is rather an identifier that points to the object, the object may still be considered "fun".

Take the following example:

```
require('nofun')
const kayla = {};
kayla.isFun(); // -> true
const dylan = kayla;
dylan.isFun; // -> true
``` 

@vuzDylan @derekerdmann

**Comment by wademauger** [comment]
I agree that if node allows us to get the variables that point to an object, we should be analyzing them for fun, but to my best knowledge, this is currently not possible.

**Comment by nickserv** [comment]
In some cases you can use `Object.prototype.constructor.name` or [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).
